-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        rounding = 14,
    },
    general = {
        allow_tearing = true,
        border_size = 2,
        col = {
            active_border = {
                colors = {"rgba(9a9996ff)", "rgba(000000ff)"},
                angle = 45,
            },
        },
        gaps_in = 2,
        gaps_out = 5,
        snap = {
            enabled = true,
        },
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
